import '../models/finance_balance.dart';
import '../models/finance_fund.dart';
import '../models/finance_recurring_item.dart';
import '../models/finance_category_template.dart';

final demoBalances = [
  FinanceBalance(
    balanceId: 'balance_matteo',
    personId: 'matteo',
    name: 'Conto principale Matteo',
    active: true,
    initialAmount: 2500,
    currentAmount: 2100,
    updatedAt: DateTime.now(),
    balanceType: FinanceBalanceType.bankAccount,
    operational: true,
    reservedAmount: 0,
    warningThreshold: 200,
    persistentStressDays: 0,
    recoveryDays: 0,
  ),
  FinanceBalance(
    balanceId: 'balance_chiara',
    personId: 'chiara',
    name: 'Conto principale Chiara',
    active: true,
    initialAmount: 1800,
    currentAmount: 1650,
    updatedAt: DateTime.now(),
    balanceType: FinanceBalanceType.bankAccount,
    operational: true,
    reservedAmount: 0,
    warningThreshold: 200,
    persistentStressDays: 0,
    recoveryDays: 0,
  ),
];

final demoFunds = [
  FinanceFund(
    id: 'emergency',
    name: 'Emergenze',
    description: 'Protezione imprevisti familiari',
    amount: 3000,
    protected: true,
    category: FinanceFundCategory.emergency,
  ),

  FinanceFund(
    id: 'car',
    name: 'Fondo Auto',
    description: 'Bollo, revisione, gomme e guasti',
    amount: 1200,
    protected: false,
    category: FinanceFundCategory.auto,
  ),
];

final demoRecurringItems = [
  FinanceRecurringItem(
    id: 'salary_matteo',
    name: 'Stipendio Matteo',
    expectedAmount: 2100,
    nextDueDate: DateTime(DateTime.now().year, DateTime.now().month, 5),
    isIncome: true,
    recurringType: FinanceRecurringType.monthly,
    category: FinanceCategory.salary,
    requiresManualConfirmation: true,
    mandatory: true,
    pressureLevel: FinancePressureLevel.low,
    confirmed: false,
    variability: FinanceVariability.fixed,
    description: 'Entrata principale stipendio Matteo',
    paymentPriority: FinancePaymentPriority.high,
    protectionLevel: FinanceProtectionLevel.protected,
    paymentOwner: FinancePaymentOwner.matteo,
    paymentMethod: FinancePaymentMethod.bankTransfer,
    stability: FinanceStability.stable,
    suspensionRisk: FinanceSuspensionRisk.low,
    originType: FinanceOriginType.manual,
    splits: const [],
  ),

  FinanceRecurringItem(
    id: 'salary_chiara',
    name: 'Stipendio Chiara',
    expectedAmount: 1800,
    nextDueDate: DateTime(DateTime.now().year, DateTime.now().month, 5),
    isIncome: true,
    recurringType: FinanceRecurringType.monthly,
    category: FinanceCategory.salary,
    requiresManualConfirmation: true,
    mandatory: true,
    pressureLevel: FinancePressureLevel.low,
    confirmed: false,
    variability: FinanceVariability.fixed,
    description: 'Entrata principale stipendio Chiara',
    paymentPriority: FinancePaymentPriority.high,
    protectionLevel: FinanceProtectionLevel.protected,
    paymentOwner: FinancePaymentOwner.chiara,
    paymentMethod: FinancePaymentMethod.bankTransfer,
    stability: FinanceStability.stable,
    suspensionRisk: FinanceSuspensionRisk.low,
    originType: FinanceOriginType.contractual,
    splits: const [],
  ),

  FinanceRecurringItem(
    id: 'netflix',
    name: 'Netflix',
    expectedAmount: 18,
    nextDueDate: DateTime.now(),
    isIncome: false,
    recurringType: FinanceRecurringType.monthly,
    category: FinanceCategory.entertainment,
    requiresManualConfirmation: false,
    mandatory: false,
    pressureLevel: FinancePressureLevel.low,
    confirmed: false,
    variability: FinanceVariability.fixed,
    description: 'Abbonamento streaming intrattenimento',
    paymentPriority: FinancePaymentPriority.low,
    protectionLevel: FinanceProtectionLevel.none,
    paymentOwner: FinancePaymentOwner.shared,
    paymentMethod: FinancePaymentMethod.rid,
    stability: FinanceStability.stable,
    suspensionRisk: FinanceSuspensionRisk.low,
    originType: FinanceOriginType.manual,
    splits: const [],
  ),
];
